apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi