apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  timeout: 5m
  releaseName: csi-driver-nfs
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/csi-driver-nfs
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: nfs-values
      valuesKey: values.yaml