apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  timeout: 5m
  releaseName: csi-driver-nfs
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/csi-driver-nfs
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m
  values:
    controller:
      resources:
        csiProvisioner:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        csiResizer:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        csiSnapshotter:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        livenessProbe:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 30Mi
        nfs:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 30Mi