apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  timeout: 5m
  releaseName: csi-driver-nfs
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.13.1"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      resources:
        csiProvisioner:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        csiResizer:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        csiSnapshotter:
          limits:
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 30Mi
        livenessProbe:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 30Mi
        nfs:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 30Mi