apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: default
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: values